# Generated by Django 5.1.6 on 2025-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
